#!/bin/bash

# Test Script for StudentId Bug Fix
# This script helps verify that the studentId issue is resolved

echo "======================================"
echo "StudentId Bug Fix - Test Guide"
echo "======================================"
echo ""
echo "Follow these steps to test the fix:"
echo ""
echo "1. START BACKEND SERVER"
echo "   cd backend && npm start"
echo ""
echo "2. START FRONTEND SERVER (in new terminal)"
echo "   npm run dev"
echo ""
echo "3. OPEN BROWSER CONSOLE (F12)"
echo "   - Keep console open throughout testing"
echo ""
echo "4. LOGIN AS STUDENT"
echo "   - Use any valid student credentials"
echo "   - Check console for 'LOGIN DEBUG' logs"
echo "   - Verify studentId is present in logs"
echo ""
echo "5. NAVIGATE TO TAKE QUIZ"
echo "   - Go to 'Take Advanced Quiz' page"
echo "   - Check console for 'Parsed student data' log"
echo "   - Check console for 'Extracted studentId' log"
echo "   - Verify studentId is NOT empty"
echo ""
echo "6. LOAD A QUIZ"
echo "   - Enter a valid quiz ID"
echo "   - Click 'Load Quiz'"
echo "   - Click 'Start Quiz'"
echo "   - Check for 'Starting quiz with studentId' log"
echo "   - Check for 'Quiz initialized with studentId' log"
echo ""
echo "7. COMPLETE AND SUBMIT QUIZ"
echo "   - Answer some questions"
echo "   - Click 'Submit Quiz'"
echo "   - Check console for 'SUBMIT DATA DEBUG' section"
echo "   - Verify all fields are populated"
echo "   - Check backend terminal for 'BACKEND SUBMIT DEBUG'"
echo ""
echo "8. VERIFY SUCCESS"
echo "   - You should see 'Quiz Submitted' toast"
echo "   - You should be redirected to results page"
echo "   - No validation errors should appear"
echo ""
echo "======================================"
echo "If you encounter errors:"
echo "======================================"
echo ""
echo "ERROR: 'Student ID not found'"
echo "  -> Clear localStorage: localStorage.clear()"
echo "  -> Re-login"
echo ""
echo "ERROR: 'Student ID is missing'"
echo "  -> Check backend logs"
echo "  -> Verify student login API returns studentId"
echo ""
echo "ERROR: 'StudentReport validation failed'"
echo "  -> Check backend console logs"
echo "  -> Verify studentId is not empty string"
echo "  -> Check if studentId is being sent in request"
echo ""
echo "======================================"
echo "Debug Commands (Browser Console):"
echo "======================================"
echo ""
echo "Check localStorage:"
echo "  localStorage.getItem('student')"
echo ""
echo "Parse and inspect:"
echo "  JSON.parse(localStorage.getItem('student'))"
echo ""
echo "Check studentId:"
echo "  JSON.parse(localStorage.getItem('student')).student.studentId"
echo ""
echo "======================================"
